### ISSUE TITLE
There is no data in your google drive link

### ISSUE THREAD

**Issue by hhwhbf** [bigtreeyanger/presence_detection_cnn#1]
Hi, I'm very interested in your work about WiFi CSI collection and CNN model train, but when I try to copy your data which you have up load to Google Drive([](https://drive.google.com/open?id=1t5fnPxIK5dpCVhSNPOnjNcPIWd0COt1U)), there is no data. Maybe the data has been deleted.
Is it convenient for you to provide your CSI data with another method?
Thank you!

**Comment by bigtreeyanger** [comment]
Hi. Thanks for your interest.  Our repo and datasets are undergoing important updates. Datasets will become available again soon. sorry for the inconvenience, will let you know once all the new data are uploaded.

**Comment by hhwhbf** [comment]
> Hi. Thanks for your interest. Our repo and datasets are undergoing important updates. Datasets will become available again soon. sorry for the inconvenience, will let you know once all the new data are uploaded.

Thank you for your reply. By the way, can I generate 4-D array by Numpy to imitate CSI signals? With 4-D array, I can learn your data-processing methods.

**Comment by bigtreeyanger** [comment]
I think It is not very easy to simulate such 4-D array because one needs to establish a model for the wireless channel and there is no straightforward way to characterize the impact of human motions on the CSI time series.

**Comment by hhwhbf** [comment]
> I think It is not very easy to simulate such 4-D array because one needs to establish a model for the wireless channel and there is no straightforward way to characterize the impact of human motions on the CSI time series.

OK, thank you! Looking forward to your new results！

**Comment by Zay2021** [comment]
Hi, I'm very interested in your work about WiFi CSI collection and CNN model train, but when I try to copy your data which you have up load to Google Drive(), there is no data. Maybe the data has been deleted.
Is it convenient for you to provide your CSI data with another method?
Thank you!
