### ISSUE TITLE
The meaning of the dimensions of the array

### ISSUE THREAD

**Issue by hhwhbf** [bigtreeyanger/presence_detection_cnn#2]
Hi, thank you for uploading the datasets. 
I used your code to parse a CSI datasets(day1,empty1). During this process, I have some questions about these different code files and different functions. 
The code "log_parsing.py" is used to parse raw CSI packet to generate frame data. Then these frame data will be send to another function named "ConstructImage" in "parse_data_from_log.py''.
Taking packet(day1,empty1) as an example, after processing it by "log_parseing.py'', I have got an list which contain CSI data and some extra information. However, the length of this list is 29357. What I am curious about is what this number represents. 
Then this list would be process by function "ConstructImage". After that, I have got a 5-D array, which has shape of 665*128*3*3*56. I guess that the number ''665'' represents the total number of seconds while the number "128'' represents how many frames per second. The number 56 represents how many subcarriers there are in total. I don't know if I guessed it right.  And what really puzzles me is that which "3" represents the transmit antennas and which "3" represents the receive antennas. 
Thank you very much!

**Comment by bigtreeyanger** [comment]
According to the paper, we use 128 consecutive CSIs to construct one CSI image for later detection which corresponds to around 1.28s measurement. The first dimension 665 means that for that test file (day1, empty1), we can generate 665 CSI images given specified step size. The first 3 represents receive antenna while the second 3 corresponds to transmit antennas. Yes, 56 stands for number of subcarriers.

**Comment by hhwhbf** [comment]
OK, thank you! So that these five dimension should be understand as : CSI images × 128 × Rx × Tx × subcarriers?

**Comment by bigtreeyanger** [comment]
correct
